# Generated by Django 4.2 on 2023-06-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='precio',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='nombre',
            new_name='title',
        ),
    ]
