# Generated by Django 4.2 on 2023-06-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_categories_coupons_rename_productos_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
