# Generated by Django 4.2 on 2023-07-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0005_products_description_products_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupons',
        ),
    ]
