# Generated by Django 4.2 on 2023-07-02 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0010_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='product_id',
            new_name='product',
        ),
    ]
